Unity game
tamamshudgubi/Ball2D pull request #1
Opened 2019-12-05 08:04 UTC by tamamshudgubi

2019-12-14 16:50 UTC, HolyMonkey requested changes

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +    public float CallDown;
Мне кажется тут имелся ввиду CoolDown

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +            gameObject.GetComponent<SpriteRenderer>().size = new Vector2(CurrentSize + 42f, 15.36f);
Получай компоненты заранее

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +            gameObject.GetComponent<SpriteRenderer>().size = new Vector2(CurrentSize + 42f, 15.36f);
Магические числа

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +            TimeToWide = CallDown;
Мне кажется тут в таймере допущена ошибка. И почему там двойка в ифе?

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/ChangeScale.cs
> +public class ChangeScale : MonoBehaviour
Тут не Change а конкретная операция

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/Coin Data.cs
> +}
Класс не имеет смысла

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/CoinsSpawner.cs
> +
Тут две линии вместо одной

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/CoinsSpawner.cs
> +            if (!CheckTrap())
Избегай ! в пользу == false

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/CoinsSpawner.cs
> +                Instantiate(Coin, new Vector3(gameObject.transform.position.x, -2.5f), Quaternion.identity);
В обоих блоках создаётся монетка. Внеси ясность в разницу этих операций

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/CoinsSpawner.cs
> +    public bool CheckTrap()
Что за ловушка и почему её проверяют?

2019-12-14 16:50 UTC, HolyMonkey commented on Assets/Scripts/Player.cs
> +public class Player : MonoBehaviour
Слишком много ответственностей у класса

2019-12-22 20:46 UTC, HolyMonkey requested changes

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +    private SpriteRenderer Renderer;
Неверная нотация

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +    public bool IsWide;
Используй [SerializeField] private

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +    private SpriteRenderer Renderer;
https://www.youtube.com/watch?v=1MvfLyBn78Q

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +
Это должно быть переменными метода а не полями

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +    private float _currentSize;
Это поле вообще используется?

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/CameraMoving.cs
> +public class Tracking : MonoBehaviour
Не отражает суть компонента

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/CameraMoving.cs
> +        _rb = GetComponent<Rigidbody2D>();
Используй RequireComponent в таких ситуациях

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/CheckForPause.cs
> +public class CheckForPause : MonoBehaviour
Pause

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/CheckForPause.cs
> +            }
Используй более явную машину состояний  (Finite State Machine)

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/GroundCheker.cs
> +        }
return Physics2D.OverlapCircle(Point.transform.position, Radius, WhatIsGround)

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +public class GroundCreator : MonoBehaviour
Не понятная ответственность класса

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +public class GroundCreator : MonoBehaviour
Этот компонент в одном экземпляре на сцене?

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/IsOnThroughPoint.cs
> +
Лишняя пустота

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +    private void Update()
Используй события

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/IsOnThroughPoint.cs
> +            BGWider.GetComponent<BackgroundWider>().IsWide = true;
Лучше вызывать методы нежели менять флаги и там в Update их будут проверять

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/LoseCheck.cs
> +        if (!IsPlayerInGame())
Используй == false вместо !

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/LoseCheck.cs
> +        if (Physics2D.OverlapBox(Point.transform.position, Size.GetComponent<BoxCollider2D>().size, Angle, WhoIsPlayer))
Так проверять в игре игрок или нет точно не стоит

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/ObstacleToRandomScale.cs
> +public class ObstacleToRandomScale : MonoBehaviour
Этот компонент не нужен. В момент создания создатель (фабрика) должен назначать случайный размер

2019-12-22 20:46 UTC, HolyMonkey commented on Assets/Scripts/ObstacleToRandomScale.cs
> +    [System.Serializable] private float _obstaclewidthMin;
Подключи систем через using. Также через одну из форм using можно резрешить конфликт с Random

2020-01-01 05:17 UTC, tamamshudgubi commented on Assets/Scripts/GroundCreator.cs
> +public class GroundCreator : MonoBehaviour
Он в одном экземпляре и объединяет в себе созданные и далее создаваемые граунды

2020-01-06 17:56 UTC, HolyMonkey requested changes

2020-01-06 17:56 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +    public SpriteRenderer Renderer;
Мы не используем публичные поля

2020-01-06 17:56 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +    public void Wide()
Wide это глагол?

2020-01-06 17:56 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +        float FixedXSize = 42f;
Переменные не называются с большой буквы

2020-01-06 17:56 UTC, HolyMonkey commented on Assets/Scripts/CameraMoving.cs
> +    private Rigidbody2D _rb;
Мы не используем сокращения

2020-01-09 21:23 UTC, HolyMonkey requested changes

2020-01-09 21:23 UTC, HolyMonkey commented on Assets/Scripts/CoinsSpawner.cs
> +public class CoinsSpawner : MonoBehaviour
Разбей пространство на сетку вместо проверок физикой. Проверка физикой - это весь хрупкой занятие. Нужно стремится к построению более предметной модели.

2020-01-14 23:57 UTC, HolyMonkey requested changes

2020-01-14 23:57 UTC, HolyMonkey commented on Assets/Scripts/BackgroundWider.cs
> +        float fixedTransfomXsize = 23.4f;
Стоит динамически высчитывать эти значения. Я так понимаю ты под картинку в ручную вбил эти значения?

2020-01-14 23:57 UTC, HolyMonkey commented on Assets/Scripts/CameraMoving.cs
> +public class CameraMoving : MonoBehaviour
У тебя камера свободно по сцене перемещается и не привязана к игроку? Если ты подобрал скорости что они движутся рядом то лучше выразить это через код

2020-01-15 00:02 UTC, HolyMonkey requested changes

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/GridObject.cs
> +    }
Используй OnValidate для этого

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +
Пробелу между этими полями не нужны

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +        _counter += _counter;
Это умножение счётчика на два?

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +    [SerializeField] private int _counter;
Почему это поле доступно для изменения?

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/IsOnThroughPoint.cs
> +public class IsOnThroughPoint : MonoBehaviour
Нужно существительное

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/IsOnThroughPoint.cs
> +    public UnityEvent CreateEvent;
Это публичное поле, мы их не делаем

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/IsOnThroughPoint.cs
> +    public UnityEvent CreateEvent;
И названия события какое-то неправильное

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/LoseCheck.cs
> +    }
Нет, лучше всё-таки использовать тригер

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/MainMenu.cs
> +    }
https://trello.com/c/HdOqpxY4/3-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B8-ui-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/Pause.cs
> +    private enum EGameStates { Play, Pause };
Зачем E? 
Множественное число тут не уместно

2020-01-15 00:02 UTC, HolyMonkey commented on Assets/Scripts/PlayerController.cs
> +    public UnityEvent TakeEvent;
Сгрупируй поля

2020-01-21 15:16 UTC, HolyMonkey requested changes

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/CameraMoving.cs
> +    }
Давай мы не будем вешать на камеру Rigidbody

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/CoinAmountText.cs
> +    private void SetCoinAmount(PlayerController player)
PlayerController тут излишне. Достаточно просто количество денег передавать

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +        Instantiate(_groundPrefab, new Vector3(_counter, _renderPoint.transform.position.y, _renderPoint.transform.position.z), Quaternion.identity);
new Vector3(_counter, _renderPoint.transform.position.y, _renderPoint.transform.position.z)

Вынеси в метод GetPosition(int number)

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +        _counter *= 2;
Почему _counter увеличивается в два раза? Ты всю землю каждый раз дублируешь? Тогда это наверное не счетчик. Не знаю, очень запутанный момент

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/IsPlayerOnThroughPoint.cs
> +    private UnityEvent GroundCreating;
Зачем приватное событие и почему поле так оформляется?

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/IsPlayerOnThroughPoint.cs
> +public class IsPlayerOnThroughPoint : MonoBehaviour
Нужно существительное

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/LosingCheck.cs
> +public class LosingCheck : MonoBehaviour
Нужно существительное

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/LosingCheck.cs
> +    private bool _isLose;
Зачем это поле? Оно же не меняется никогда? И по умолчанию false

2020-01-21 15:16 UTC, HolyMonkey commented on Assets/Scripts/LosingCheck.cs
> +    private IEnumerator SetLosingState(PlayerController player)
Почему это корутина?

2020-01-24 13:12 UTC, HolyMonkey requested changes

2020-01-24 13:12 UTC, HolyMonkey commented on Assets/Scripts/CoinAmountText.cs
> +        _player.GetCurrentCoinAmount += SetCoinAmount;
https://trello.com/c/CsOZfMhi/1-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2

2020-01-24 13:12 UTC, HolyMonkey commented on Assets/Scripts/GroundCreator.cs
> +    [SerializeField] private int _nextGroundNumber = 1;
Почему это [SerializeField]?

2020-01-24 13:12 UTC, HolyMonkey commented on Assets/Scripts/PlayerController.cs
> +    [SerializeField] private ObstacleCheker _obstacleCheker;
Checker

2020-02-09 00:08 UTC, merged